config/routes.rb
Rails.application.routes.draw do

  #
  # get 'books/index'
  # get 'books/new'
  # get 'books/show'
  # get 'books/create'
  # get 'books/edit'
  # get 'books/update'
  # get 'books/delete'
  resources :authors
    resources :books




  root 'authors#index'
  # get 'authors/index'
  # get 'authors/new'
  # get 'authors/show'
  # get 'authors/create'
  # get 'authors/edit'
  # get 'authors/update'
  # get 'authors/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author = Author.all
  end

  def new
   @author = Author.new






  end

  def show
    id = params[:id]
    @author = Author.find(id)

  end


  def create
    @author = Author.new(authors_params)
    # ...
  end

  public
    def authors_params
      params.require(:Author).permit(:first_name, :last_name)
    end



  def edit
  end

  def update
  end

  def destroy
    @article = Author.find(params[:id])
  @article.destroy

  redirect_to authors_path, notice: "Deletion has been succesful"
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.all
  end

  def new

  end

  def show
    id = params[:id]
    @book = Book.find(id)
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def first_name:string
  end

  def last_name:string
  end

  def age:integer
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/authors/_form.html.erb
<h1>FORM PRETEND</h1>

<%= form_for @author, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<h1>firs name</h1>  <%= f.text_area :first_name, size: "60x12"%>
<h1>last name</h1>  <%= f.text_area :last_name, size: "60x12" %>
<h1>age</h1>  <%= f.text_area :age, size: "60x12" %>

  <%= f.submit "Create" %>
<% end %>

<!-- form_tag(search_path, method: "patch") -->

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/delete.html.erb
<h1>Authors#delete</h1>
<p>Find me in app/views/authors/delete.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>


<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>THIS IS THE HOMEPAGE</h1>






  <% @author.each do |user| %>


  <p>
    Author:
    <%= user.first_name %>
    <%= user.last_name %></p>
  <p>
    Age
    <%= user.age %></p><br>

    <%= link_to 'Edit', edit_author_path(user) %>
      <%= link_to 'Show', user %>
      <%= link_to 'Delete',
                   author_path(user),
                               method: :delete,
                               data: { confirm: 'Are you sure?' } %>
    <% end %><br>

<br><%= link_to 'New_author', new_author_path %>
<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/articles/1">Delete</a>
<!-- <div class="notice">Delete success</div> -->

app/views/authors/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1>Authors</h1>
<p> <%= @author.first_name %> <%= @author.last_name %> </p>
<p> <%= @author.age %> </p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/delete.html.erb
<h1>Books#delete</h1>
<p>Find me in app/views/books/delete.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>


<% @book.each do |books| %>
  <h1>
    <%= books.title %></h1>
  <p>description: <%= books.description %></p>
  <p>pages: <%= books.page_number %> </p>

<%end%>



<br>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books</h1>
<p> <%= @book.title %> <%= @book.description %> </p>
<p> <%= @book.page_number %> </p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksRelationships</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- for the delete message -->
    <% flash.each do |name, msg| -%>
     <%= content_tag :div, msg, class: name %>
<% end -%>

    <%= yield %>
  </body>

</html>